import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Login from './components/auth/Login'
import ProtectedRoute from './components/auth/ProtectedRoute'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Inventory Dashboard",
  description: "Generated by Ahmed Salman",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ProtectedRoute>
          <div className="min-h-screen bg-gray-100">
            {/* Navigation */}
            <nav className="bg-white shadow-sm">
              <div className="max-w-7xl mx-auto px-4">
                <div className="flex justify-between h-16">
                  <div className="flex items-center">
                    <h1 className="text-xl font-bold">Inventory Dashboard</h1>
                  </div>
                  {/* Add navigation items here later */}
                </div>
              </div>
            </nav>

            {/* Main Content */}
            <main className="max-w-7xl mx-auto py-6 px-4">
              {children}
            </main>
          </div>
        </ProtectedRoute>
      </body>
    </html>
  );
}